name: Update Charging Station Data

on:
  schedule:
    - cron: "*/5 * * * *"  # 매 5분마다 실행
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 클론
        uses: actions/checkout@v4

      - name: Python 환경 설정
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 의존성 설치
        run: pip install -r requirements.txt

      - name: 환경 변수 설정 (Supabase)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: echo "Supabase 환경 변수 설정 완료"

      - name: Charging API 실행
        run: python Charging_API.py